// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN7p0aNPLxY3MqLYYnfR_zf_DeL5JiXIE',
    appId: '1:740479042970:web:e6504ed1d0fd6a3d5fe623',
    messagingSenderId: '740479042970',
    projectId: 'hackathon-5cd60',
    authDomain: 'hackathon-5cd60.firebaseapp.com',
    storageBucket: 'hackathon-5cd60.appspot.com',
    measurementId: 'G-VNLCV0XD0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAY2HihieBKQUmB1sucuzxdl7DWRuDl5U',
    appId: '1:740479042970:android:e25217790a1132a45fe623',
    messagingSenderId: '740479042970',
    projectId: 'hackathon-5cd60',
    storageBucket: 'hackathon-5cd60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjJ_7Nnc6kHUdveq-Y0we2SYTNcgNwDK8',
    appId: '1:740479042970:ios:7365e7f375913b365fe623',
    messagingSenderId: '740479042970',
    projectId: 'hackathon-5cd60',
    storageBucket: 'hackathon-5cd60.appspot.com',
    iosBundleId: 'com.example.chunavganit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjJ_7Nnc6kHUdveq-Y0we2SYTNcgNwDK8',
    appId: '1:740479042970:ios:7365e7f375913b365fe623',
    messagingSenderId: '740479042970',
    projectId: 'hackathon-5cd60',
    storageBucket: 'hackathon-5cd60.appspot.com',
    iosBundleId: 'com.example.chunavganit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN7p0aNPLxY3MqLYYnfR_zf_DeL5JiXIE',
    appId: '1:740479042970:web:800cee1a27b7860c5fe623',
    messagingSenderId: '740479042970',
    projectId: 'hackathon-5cd60',
    authDomain: 'hackathon-5cd60.firebaseapp.com',
    storageBucket: 'hackathon-5cd60.appspot.com',
    measurementId: 'G-31H4F52SZT',
  );
}
